import { test, expect } from '@playwright/test'
import { client, uniqueEmail, verified } from './helpers'
import { countries } from '../src/shared/countries'

test('country search, keyboard selection, dismissal and mobile dropdown bounds', async ({
  page,
}) => {
  const owner = await client()
  await verified(owner, uniqueEmail('dropdown'))
  await page.context().addCookies((await owner.storageState()).cookies)
  await page.goto('/onboarding/company')
  const location = page.getByRole('button', { name: /Location/ })
  await location.click()
  const search = page.getByRole('combobox', { name: 'Search countries' })
  await expect(search).toBeFocused()
  await expect(page.getByRole('option')).toHaveCount(249)
  await expect(page.getByRole('option').first()).toHaveText('Indonesia')
  expect(new Set(countries).size).toBe(249)
  expect(countries.slice(1)).toEqual(
    [...countries.slice(1)].sort((a, b) => a.localeCompare(b, 'en')),
  )
  await search.fill('aland islands')
  await expect(page.getByRole('option')).toHaveCount(1)
  await expect(page.getByRole('option')).toHaveText('Åland Islands')
  await search.fill('zzzz')
  await expect(page.getByText('No countries found')).toBeVisible()
  await search.press('Enter')
  await expect(search).toBeVisible()
  await page.getByRole('button', { name: 'Clear search' }).click()
  await expect(search).toBeFocused()
  await expect(page.getByRole('option')).toHaveCount(249)
  await search.fill('united')
  await expect(page.getByRole('option', { name: 'United Kingdom', exact: true })).toBeVisible()
  await search.press('ArrowDown')
  await search.press('Enter')
  await expect(location).toContainText('United Kingdom')
  await expect(location).toBeFocused()
  await location.click()
  await search.fill('Japan')
  await search.press('Escape')
  await expect(location).toContainText('United Kingdom')
  await expect(location).toBeFocused()
  await location.click()
  await search.press('Tab')
  await expect(page.getByRole('combobox', { name: /Industry/ })).toBeFocused()
  await expect(search).not.toBeVisible()
  const industry = page.getByRole('combobox', { name: /Industry/ })
  await industry.press('ArrowDown')
  await industry.press('End')
  await industry.press('Enter')
  await expect(industry).toContainText('Other')
  await industry.click()
  await page.getByRole('heading', { name: 'Tell us about your company' }).click()
  await expect(page.getByRole('listbox')).not.toBeVisible()
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 844 })
    await location.click()
    const panel = page.locator('.select-popup')
    await expect(panel).toBeVisible()
    const box = (await panel.boundingBox())!
    expect(box.x).toBeGreaterThanOrEqual(0)
    expect(box.x + box.width).toBeLessThanOrEqual(width)
    expect(box.y).toBeGreaterThanOrEqual(0)
    expect(box.y + box.height).toBeLessThanOrEqual(844)
    expect(box.height).toBeLessThanOrEqual(300)
    await search.fill('Indonesia')
    await page.screenshot({ path: `test-results/dropdown-${width}.png` })
    await search.press('Enter')
    await expect(location).toContainText('Indonesia')
  }
  await owner.dispose()
})
